### ISSUE TITLE
react-native-reanimated

### ISSUE THREAD

**Issue by AElbert** [codesbiome/electron-react-webpack-typescript-2023#51]
Add to the project react-native-web, I set this
```
alias: {
  // Custom Aliases
  'react-native$': 'react-native-web', //this
  ...require('./webpack.aliases'),
},
```
in `webpack.renderer.js`

Now I'm trying to use react-native reanimated but I'm having difficulties, the installation is like this: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation

I created a `.babelrc` file this is the content:
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    ["react-native-web", { "commonjs": true }],
    "@babel/plugin-proposal-export-namespace-from",
    ["react-native-reanimated/plugin", {
      "relativeSourceLocation": true
    }]
  ]
}
```

and specify it in `webpack.rules.js`:
```
module.exports = [
  {
    test: /\.(tsx|ts|jsx|js)$/,
    exclude: /node_modules/,
    use: {
      loader: 'babel-loader',
    },
  },
  ...
];
```

But I get the following error:
```
Module parse failed: Unexpected token (511:20)
node_modules/react-native-reanimated/lib/createAnimatedComponent.js
File was processed with these loaders:
 * ../../node_modules/@vercel/webpack-asset-relocator-loader/dist/index.js
You may need an additional loader to handle the result of these loaders.
|                 default: { collapsable: false },
|             });
>             return ();
|         }
|     }
 ```
Any idea how to fix it?
I tried it in a next.js project it works without problems

**Comment by codesbiome** [comment]
The errors you mentioned were caused due to some additional loader requirement for those `react-native-animated` modules.

Have you tried using existing [documentation](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/web-support/#webpack-support) regarding webpack support of that plugin?

**Comment by AElbert** [comment]
I made some changes to the webpack rule and added this setting:

```
entry: [
  'babel-polyfill',
  './src/main/app.ts'
]
```
in `webpack.main.js` pero seguia obteniendo un error, asi que tambien lo agregue en `webpack.renderer.js` asi:
```
entry: [
  'babel-polyfill',
]
```

I also added `new webpack.EnvironmentPlugin({ JEST_WORKER_ID: null })` to `webpack.plugins.js`, I only added that one because if I add `new webpack.DefinePlugin({ process: { env: { env: {} } })` I get this error: 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'chrome')
    at appPreload.tsx:16:38
```

And that's because `new webpack.DefinePlugin({ process: { process: { env: {} } })` sets `env` to `{}` and in `appPreload.tsx` it's used like this 
```
// Process versions
for (const type of ['chrome', 'node', 'electron']) {
  versions[type] = process.versions[type];
}
```

Configure all this as described in the reanimated documentation on webpack https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/web-support/#webpack-support

After configuring all this, finally the app worked without errors but now no component is rendered, just a blank screen.

any idea how to fix it?
