### ISSUE TITLE
Package cannot run after using typeorm+better-sqlite3

### ISSUE THREAD

**Issue by l1985q** [codesbiome/electron-react-webpack-typescript-2023#58]
When I use this framework for development, I use typeorm+better-sqlite3, and it runs normally during debugging. But after performing npm run package packaging operation, the database cannot be accessed. My development environment is windows 10. How to solve it? Thanks!

**Comment by codesbiome** [comment]
Hello @l1985q 

If you can provide a temporary repository to replicate the issue you facing, that'd be really helpful.
